/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AllocationsRouteImport } from './routes/allocations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VariationsIndexRouteImport } from './routes/variations.index'
import { Route as UtilisationIndexRouteImport } from './routes/utilisation.index'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as SitesIndexRouteImport } from './routes/sites.index'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SafetyIndexRouteImport } from './routes/safety.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ProcureIndexRouteImport } from './routes/procure.index'
import { Route as PlantIndexRouteImport } from './routes/plant.index'
import { Route as PilesIndexRouteImport } from './routes/piles.index'
import { Route as CrewIndexRouteImport } from './routes/crew.index'
import { Route as ComplianceIndexRouteImport } from './routes/compliance.index'
import { Route as VariationsIdRouteImport } from './routes/variations.$id'
import { Route as SitesIdRouteImport } from './routes/sites.$id'
import { Route as ReportsExportRouteImport } from './routes/reports.export'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as ProcureSuppliersRouteImport } from './routes/procure.suppliers'
import { Route as ProcureQuotesRouteImport } from './routes/procure.quotes'
import { Route as ProcureEquipmentRouteImport } from './routes/procure.equipment'
import { Route as PlantIdRouteImport } from './routes/plant.$id'
import { Route as PilesRatesRouteImport } from './routes/piles.rates'
import { Route as CrewIdRouteImport } from './routes/crew.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PeopleTrainingIndexRouteImport } from './routes/people.training.index'
import { Route as PeopleTeamIndexRouteImport } from './routes/people.team.index'
import { Route as PeopleRolesIndexRouteImport } from './routes/people.roles.index'
import { Route as PlantIdPrestartRouteImport } from './routes/plant.$id.prestart'
import { Route as ApiPublicSlackWebhookRouteImport } from './routes/api/public/slack-webhook'
import { Route as AllocationsWrapDateRouteImport } from './routes/allocations.wrap.$date'
import { Route as ApiPublicReportsPdfRouteImport } from './routes/api/public/reports.pdf'
import { Route as ApiPublicProcurePollGmailRouteImport } from './routes/api/public/procure/poll-gmail'
import { Route as ApiPublicHooksRecomputeReportRouteImport } from './routes/api/public/hooks/recompute-report'
import { Route as ApiPublicHooksPrestartMorningDmRouteImport } from './routes/api/public/hooks/prestart-morning-dm'
import { Route as ApiPublicHooksPrestartMissingRouteImport } from './routes/api/public/hooks/prestart-missing'
import { Route as ApiPublicHooksInductionExpirySweepRouteImport } from './routes/api/public/hooks/induction-expiry-sweep'
import { Route as ApiPublicHooksDailyPromptRouteImport } from './routes/api/public/hooks/daily-prompt'
import { Route as ApiPublicHooksAllocationEligibilityRouteImport } from './routes/api/public/hooks/allocation-eligibility'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsRoute = AllocationsRouteImport.update({
  id: '/allocations',
  path: '/allocations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariationsIndexRoute = VariationsIndexRouteImport.update({
  id: '/variations/',
  path: '/variations/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisationIndexRoute = UtilisationIndexRouteImport.update({
  id: '/utilisation/',
  path: '/utilisation/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyIndexRoute = SafetyIndexRouteImport.update({
  id: '/safety/',
  path: '/safety/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcureIndexRoute = ProcureIndexRouteImport.update({
  id: '/procure/',
  path: '/procure/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantIndexRoute = PlantIndexRouteImport.update({
  id: '/plant/',
  path: '/plant/',
  getParentRoute: () => rootRouteImport,
} as any)
const PilesIndexRoute = PilesIndexRouteImport.update({
  id: '/piles/',
  path: '/piles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIndexRoute = CrewIndexRouteImport.update({
  id: '/crew/',
  path: '/crew/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/compliance/',
  path: '/compliance/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariationsIdRoute = VariationsIdRouteImport.update({
  id: '/variations/$id',
  path: '/variations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIdRoute = SitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExportRoute = ReportsExportRouteImport.update({
  id: '/reports/export',
  path: '/reports/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcureSuppliersRoute = ProcureSuppliersRouteImport.update({
  id: '/procure/suppliers',
  path: '/procure/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcureQuotesRoute = ProcureQuotesRouteImport.update({
  id: '/procure/quotes',
  path: '/procure/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcureEquipmentRoute = ProcureEquipmentRouteImport.update({
  id: '/procure/equipment',
  path: '/procure/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantIdRoute = PlantIdRouteImport.update({
  id: '/plant/$id',
  path: '/plant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PilesRatesRoute = PilesRatesRouteImport.update({
  id: '/piles/rates',
  path: '/piles/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIdRoute = CrewIdRouteImport.update({
  id: '/crew/$id',
  path: '/crew/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleTrainingIndexRoute = PeopleTrainingIndexRouteImport.update({
  id: '/people/training/',
  path: '/people/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleTeamIndexRoute = PeopleTeamIndexRouteImport.update({
  id: '/people/team/',
  path: '/people/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRolesIndexRoute = PeopleRolesIndexRouteImport.update({
  id: '/people/roles/',
  path: '/people/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantIdPrestartRoute = PlantIdPrestartRouteImport.update({
  id: '/prestart',
  path: '/prestart',
  getParentRoute: () => PlantIdRoute,
} as any)
const ApiPublicSlackWebhookRoute = ApiPublicSlackWebhookRouteImport.update({
  id: '/api/public/slack-webhook',
  path: '/api/public/slack-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsWrapDateRoute = AllocationsWrapDateRouteImport.update({
  id: '/wrap/$date',
  path: '/wrap/$date',
  getParentRoute: () => AllocationsRoute,
} as any)
const ApiPublicReportsPdfRoute = ApiPublicReportsPdfRouteImport.update({
  id: '/api/public/reports/pdf',
  path: '/api/public/reports/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcurePollGmailRoute =
  ApiPublicProcurePollGmailRouteImport.update({
    id: '/api/public/procure/poll-gmail',
    path: '/api/public/procure/poll-gmail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecomputeReportRoute =
  ApiPublicHooksRecomputeReportRouteImport.update({
    id: '/api/public/hooks/recompute-report',
    path: '/api/public/hooks/recompute-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPrestartMorningDmRoute =
  ApiPublicHooksPrestartMorningDmRouteImport.update({
    id: '/api/public/hooks/prestart-morning-dm',
    path: '/api/public/hooks/prestart-morning-dm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPrestartMissingRoute =
  ApiPublicHooksPrestartMissingRouteImport.update({
    id: '/api/public/hooks/prestart-missing',
    path: '/api/public/hooks/prestart-missing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInductionExpirySweepRoute =
  ApiPublicHooksInductionExpirySweepRouteImport.update({
    id: '/api/public/hooks/induction-expiry-sweep',
    path: '/api/public/hooks/induction-expiry-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyPromptRoute =
  ApiPublicHooksDailyPromptRouteImport.update({
    id: '/api/public/hooks/daily-prompt',
    path: '/api/public/hooks/daily-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAllocationEligibilityRoute =
  ApiPublicHooksAllocationEligibilityRouteImport.update({
    id: '/api/public/hooks/allocation-eligibility',
    path: '/api/public/hooks/allocation-eligibility',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/today': typeof TodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/crew/$id': typeof CrewIdRoute
  '/piles/rates': typeof PilesRatesRoute
  '/plant/$id': typeof PlantIdRouteWithChildren
  '/procure/equipment': typeof ProcureEquipmentRoute
  '/procure/quotes': typeof ProcureQuotesRoute
  '/procure/suppliers': typeof ProcureSuppliersRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/export': typeof ReportsExportRoute
  '/sites/$id': typeof SitesIdRoute
  '/variations/$id': typeof VariationsIdRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/crew/': typeof CrewIndexRoute
  '/piles/': typeof PilesIndexRoute
  '/plant/': typeof PlantIndexRoute
  '/procure/': typeof ProcureIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/sites/': typeof SitesIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/utilisation/': typeof UtilisationIndexRoute
  '/variations/': typeof VariationsIndexRoute
  '/allocations/wrap/$date': typeof AllocationsWrapDateRoute
  '/api/public/slack-webhook': typeof ApiPublicSlackWebhookRoute
  '/plant/$id/prestart': typeof PlantIdPrestartRoute
  '/people/roles/': typeof PeopleRolesIndexRoute
  '/people/team/': typeof PeopleTeamIndexRoute
  '/people/training/': typeof PeopleTrainingIndexRoute
  '/api/public/hooks/allocation-eligibility': typeof ApiPublicHooksAllocationEligibilityRoute
  '/api/public/hooks/daily-prompt': typeof ApiPublicHooksDailyPromptRoute
  '/api/public/hooks/induction-expiry-sweep': typeof ApiPublicHooksInductionExpirySweepRoute
  '/api/public/hooks/prestart-missing': typeof ApiPublicHooksPrestartMissingRoute
  '/api/public/hooks/prestart-morning-dm': typeof ApiPublicHooksPrestartMorningDmRoute
  '/api/public/hooks/recompute-report': typeof ApiPublicHooksRecomputeReportRoute
  '/api/public/procure/poll-gmail': typeof ApiPublicProcurePollGmailRoute
  '/api/public/reports/pdf': typeof ApiPublicReportsPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/today': typeof TodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/crew/$id': typeof CrewIdRoute
  '/piles/rates': typeof PilesRatesRoute
  '/plant/$id': typeof PlantIdRouteWithChildren
  '/procure/equipment': typeof ProcureEquipmentRoute
  '/procure/quotes': typeof ProcureQuotesRoute
  '/procure/suppliers': typeof ProcureSuppliersRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/export': typeof ReportsExportRoute
  '/sites/$id': typeof SitesIdRoute
  '/variations/$id': typeof VariationsIdRoute
  '/compliance': typeof ComplianceIndexRoute
  '/crew': typeof CrewIndexRoute
  '/piles': typeof PilesIndexRoute
  '/plant': typeof PlantIndexRoute
  '/procure': typeof ProcureIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/safety': typeof SafetyIndexRoute
  '/setup': typeof SetupIndexRoute
  '/sites': typeof SitesIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/utilisation': typeof UtilisationIndexRoute
  '/variations': typeof VariationsIndexRoute
  '/allocations/wrap/$date': typeof AllocationsWrapDateRoute
  '/api/public/slack-webhook': typeof ApiPublicSlackWebhookRoute
  '/plant/$id/prestart': typeof PlantIdPrestartRoute
  '/people/roles': typeof PeopleRolesIndexRoute
  '/people/team': typeof PeopleTeamIndexRoute
  '/people/training': typeof PeopleTrainingIndexRoute
  '/api/public/hooks/allocation-eligibility': typeof ApiPublicHooksAllocationEligibilityRoute
  '/api/public/hooks/daily-prompt': typeof ApiPublicHooksDailyPromptRoute
  '/api/public/hooks/induction-expiry-sweep': typeof ApiPublicHooksInductionExpirySweepRoute
  '/api/public/hooks/prestart-missing': typeof ApiPublicHooksPrestartMissingRoute
  '/api/public/hooks/prestart-morning-dm': typeof ApiPublicHooksPrestartMorningDmRoute
  '/api/public/hooks/recompute-report': typeof ApiPublicHooksRecomputeReportRoute
  '/api/public/procure/poll-gmail': typeof ApiPublicProcurePollGmailRoute
  '/api/public/reports/pdf': typeof ApiPublicReportsPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/today': typeof TodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/crew/$id': typeof CrewIdRoute
  '/piles/rates': typeof PilesRatesRoute
  '/plant/$id': typeof PlantIdRouteWithChildren
  '/procure/equipment': typeof ProcureEquipmentRoute
  '/procure/quotes': typeof ProcureQuotesRoute
  '/procure/suppliers': typeof ProcureSuppliersRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/export': typeof ReportsExportRoute
  '/sites/$id': typeof SitesIdRoute
  '/variations/$id': typeof VariationsIdRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/crew/': typeof CrewIndexRoute
  '/piles/': typeof PilesIndexRoute
  '/plant/': typeof PlantIndexRoute
  '/procure/': typeof ProcureIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/sites/': typeof SitesIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/utilisation/': typeof UtilisationIndexRoute
  '/variations/': typeof VariationsIndexRoute
  '/allocations/wrap/$date': typeof AllocationsWrapDateRoute
  '/api/public/slack-webhook': typeof ApiPublicSlackWebhookRoute
  '/plant/$id/prestart': typeof PlantIdPrestartRoute
  '/people/roles/': typeof PeopleRolesIndexRoute
  '/people/team/': typeof PeopleTeamIndexRoute
  '/people/training/': typeof PeopleTrainingIndexRoute
  '/api/public/hooks/allocation-eligibility': typeof ApiPublicHooksAllocationEligibilityRoute
  '/api/public/hooks/daily-prompt': typeof ApiPublicHooksDailyPromptRoute
  '/api/public/hooks/induction-expiry-sweep': typeof ApiPublicHooksInductionExpirySweepRoute
  '/api/public/hooks/prestart-missing': typeof ApiPublicHooksPrestartMissingRoute
  '/api/public/hooks/prestart-morning-dm': typeof ApiPublicHooksPrestartMorningDmRoute
  '/api/public/hooks/recompute-report': typeof ApiPublicHooksRecomputeReportRoute
  '/api/public/procure/poll-gmail': typeof ApiPublicProcurePollGmailRoute
  '/api/public/reports/pdf': typeof ApiPublicReportsPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocations'
    | '/forgot-password'
    | '/login'
    | '/overview'
    | '/reset-password'
    | '/signup'
    | '/today'
    | '/auth/callback'
    | '/crew/$id'
    | '/piles/rates'
    | '/plant/$id'
    | '/procure/equipment'
    | '/procure/quotes'
    | '/procure/suppliers'
    | '/reports/$id'
    | '/reports/export'
    | '/sites/$id'
    | '/variations/$id'
    | '/compliance/'
    | '/crew/'
    | '/piles/'
    | '/plant/'
    | '/procure/'
    | '/reports/'
    | '/safety/'
    | '/setup/'
    | '/sites/'
    | '/tickets/'
    | '/utilisation/'
    | '/variations/'
    | '/allocations/wrap/$date'
    | '/api/public/slack-webhook'
    | '/plant/$id/prestart'
    | '/people/roles/'
    | '/people/team/'
    | '/people/training/'
    | '/api/public/hooks/allocation-eligibility'
    | '/api/public/hooks/daily-prompt'
    | '/api/public/hooks/induction-expiry-sweep'
    | '/api/public/hooks/prestart-missing'
    | '/api/public/hooks/prestart-morning-dm'
    | '/api/public/hooks/recompute-report'
    | '/api/public/procure/poll-gmail'
    | '/api/public/reports/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocations'
    | '/forgot-password'
    | '/login'
    | '/overview'
    | '/reset-password'
    | '/signup'
    | '/today'
    | '/auth/callback'
    | '/crew/$id'
    | '/piles/rates'
    | '/plant/$id'
    | '/procure/equipment'
    | '/procure/quotes'
    | '/procure/suppliers'
    | '/reports/$id'
    | '/reports/export'
    | '/sites/$id'
    | '/variations/$id'
    | '/compliance'
    | '/crew'
    | '/piles'
    | '/plant'
    | '/procure'
    | '/reports'
    | '/safety'
    | '/setup'
    | '/sites'
    | '/tickets'
    | '/utilisation'
    | '/variations'
    | '/allocations/wrap/$date'
    | '/api/public/slack-webhook'
    | '/plant/$id/prestart'
    | '/people/roles'
    | '/people/team'
    | '/people/training'
    | '/api/public/hooks/allocation-eligibility'
    | '/api/public/hooks/daily-prompt'
    | '/api/public/hooks/induction-expiry-sweep'
    | '/api/public/hooks/prestart-missing'
    | '/api/public/hooks/prestart-morning-dm'
    | '/api/public/hooks/recompute-report'
    | '/api/public/procure/poll-gmail'
    | '/api/public/reports/pdf'
  id:
    | '__root__'
    | '/'
    | '/allocations'
    | '/forgot-password'
    | '/login'
    | '/overview'
    | '/reset-password'
    | '/signup'
    | '/today'
    | '/auth/callback'
    | '/crew/$id'
    | '/piles/rates'
    | '/plant/$id'
    | '/procure/equipment'
    | '/procure/quotes'
    | '/procure/suppliers'
    | '/reports/$id'
    | '/reports/export'
    | '/sites/$id'
    | '/variations/$id'
    | '/compliance/'
    | '/crew/'
    | '/piles/'
    | '/plant/'
    | '/procure/'
    | '/reports/'
    | '/safety/'
    | '/setup/'
    | '/sites/'
    | '/tickets/'
    | '/utilisation/'
    | '/variations/'
    | '/allocations/wrap/$date'
    | '/api/public/slack-webhook'
    | '/plant/$id/prestart'
    | '/people/roles/'
    | '/people/team/'
    | '/people/training/'
    | '/api/public/hooks/allocation-eligibility'
    | '/api/public/hooks/daily-prompt'
    | '/api/public/hooks/induction-expiry-sweep'
    | '/api/public/hooks/prestart-missing'
    | '/api/public/hooks/prestart-morning-dm'
    | '/api/public/hooks/recompute-report'
    | '/api/public/procure/poll-gmail'
    | '/api/public/reports/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationsRoute: typeof AllocationsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TodayRoute: typeof TodayRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CrewIdRoute: typeof CrewIdRoute
  PilesRatesRoute: typeof PilesRatesRoute
  PlantIdRoute: typeof PlantIdRouteWithChildren
  ProcureEquipmentRoute: typeof ProcureEquipmentRoute
  ProcureQuotesRoute: typeof ProcureQuotesRoute
  ProcureSuppliersRoute: typeof ProcureSuppliersRoute
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsExportRoute: typeof ReportsExportRoute
  SitesIdRoute: typeof SitesIdRoute
  VariationsIdRoute: typeof VariationsIdRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
  CrewIndexRoute: typeof CrewIndexRoute
  PilesIndexRoute: typeof PilesIndexRoute
  PlantIndexRoute: typeof PlantIndexRoute
  ProcureIndexRoute: typeof ProcureIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SafetyIndexRoute: typeof SafetyIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  SitesIndexRoute: typeof SitesIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  UtilisationIndexRoute: typeof UtilisationIndexRoute
  VariationsIndexRoute: typeof VariationsIndexRoute
  ApiPublicSlackWebhookRoute: typeof ApiPublicSlackWebhookRoute
  PeopleRolesIndexRoute: typeof PeopleRolesIndexRoute
  PeopleTeamIndexRoute: typeof PeopleTeamIndexRoute
  PeopleTrainingIndexRoute: typeof PeopleTrainingIndexRoute
  ApiPublicHooksAllocationEligibilityRoute: typeof ApiPublicHooksAllocationEligibilityRoute
  ApiPublicHooksDailyPromptRoute: typeof ApiPublicHooksDailyPromptRoute
  ApiPublicHooksInductionExpirySweepRoute: typeof ApiPublicHooksInductionExpirySweepRoute
  ApiPublicHooksPrestartMissingRoute: typeof ApiPublicHooksPrestartMissingRoute
  ApiPublicHooksPrestartMorningDmRoute: typeof ApiPublicHooksPrestartMorningDmRoute
  ApiPublicHooksRecomputeReportRoute: typeof ApiPublicHooksRecomputeReportRoute
  ApiPublicProcurePollGmailRoute: typeof ApiPublicProcurePollGmailRoute
  ApiPublicReportsPdfRoute: typeof ApiPublicReportsPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations': {
      id: '/allocations'
      path: '/allocations'
      fullPath: '/allocations'
      preLoaderRoute: typeof AllocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variations/': {
      id: '/variations/'
      path: '/variations'
      fullPath: '/variations/'
      preLoaderRoute: typeof VariationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisation/': {
      id: '/utilisation/'
      path: '/utilisation'
      fullPath: '/utilisation/'
      preLoaderRoute: typeof UtilisationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/': {
      id: '/safety/'
      path: '/safety'
      fullPath: '/safety/'
      preLoaderRoute: typeof SafetyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procure/': {
      id: '/procure/'
      path: '/procure'
      fullPath: '/procure/'
      preLoaderRoute: typeof ProcureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant/': {
      id: '/plant/'
      path: '/plant'
      fullPath: '/plant/'
      preLoaderRoute: typeof PlantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piles/': {
      id: '/piles/'
      path: '/piles'
      fullPath: '/piles/'
      preLoaderRoute: typeof PilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/': {
      id: '/crew/'
      path: '/crew'
      fullPath: '/crew/'
      preLoaderRoute: typeof CrewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variations/$id': {
      id: '/variations/$id'
      path: '/variations/$id'
      fullPath: '/variations/$id'
      preLoaderRoute: typeof VariationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$id': {
      id: '/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof SitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/export': {
      id: '/reports/export'
      path: '/reports/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof ReportsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procure/suppliers': {
      id: '/procure/suppliers'
      path: '/procure/suppliers'
      fullPath: '/procure/suppliers'
      preLoaderRoute: typeof ProcureSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procure/quotes': {
      id: '/procure/quotes'
      path: '/procure/quotes'
      fullPath: '/procure/quotes'
      preLoaderRoute: typeof ProcureQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procure/equipment': {
      id: '/procure/equipment'
      path: '/procure/equipment'
      fullPath: '/procure/equipment'
      preLoaderRoute: typeof ProcureEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant/$id': {
      id: '/plant/$id'
      path: '/plant/$id'
      fullPath: '/plant/$id'
      preLoaderRoute: typeof PlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piles/rates': {
      id: '/piles/rates'
      path: '/piles/rates'
      fullPath: '/piles/rates'
      preLoaderRoute: typeof PilesRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/$id': {
      id: '/crew/$id'
      path: '/crew/$id'
      fullPath: '/crew/$id'
      preLoaderRoute: typeof CrewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/training/': {
      id: '/people/training/'
      path: '/people/training'
      fullPath: '/people/training/'
      preLoaderRoute: typeof PeopleTrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/team/': {
      id: '/people/team/'
      path: '/people/team'
      fullPath: '/people/team/'
      preLoaderRoute: typeof PeopleTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/roles/': {
      id: '/people/roles/'
      path: '/people/roles'
      fullPath: '/people/roles/'
      preLoaderRoute: typeof PeopleRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant/$id/prestart': {
      id: '/plant/$id/prestart'
      path: '/prestart'
      fullPath: '/plant/$id/prestart'
      preLoaderRoute: typeof PlantIdPrestartRouteImport
      parentRoute: typeof PlantIdRoute
    }
    '/api/public/slack-webhook': {
      id: '/api/public/slack-webhook'
      path: '/api/public/slack-webhook'
      fullPath: '/api/public/slack-webhook'
      preLoaderRoute: typeof ApiPublicSlackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations/wrap/$date': {
      id: '/allocations/wrap/$date'
      path: '/wrap/$date'
      fullPath: '/allocations/wrap/$date'
      preLoaderRoute: typeof AllocationsWrapDateRouteImport
      parentRoute: typeof AllocationsRoute
    }
    '/api/public/reports/pdf': {
      id: '/api/public/reports/pdf'
      path: '/api/public/reports/pdf'
      fullPath: '/api/public/reports/pdf'
      preLoaderRoute: typeof ApiPublicReportsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/procure/poll-gmail': {
      id: '/api/public/procure/poll-gmail'
      path: '/api/public/procure/poll-gmail'
      fullPath: '/api/public/procure/poll-gmail'
      preLoaderRoute: typeof ApiPublicProcurePollGmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recompute-report': {
      id: '/api/public/hooks/recompute-report'
      path: '/api/public/hooks/recompute-report'
      fullPath: '/api/public/hooks/recompute-report'
      preLoaderRoute: typeof ApiPublicHooksRecomputeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/prestart-morning-dm': {
      id: '/api/public/hooks/prestart-morning-dm'
      path: '/api/public/hooks/prestart-morning-dm'
      fullPath: '/api/public/hooks/prestart-morning-dm'
      preLoaderRoute: typeof ApiPublicHooksPrestartMorningDmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/prestart-missing': {
      id: '/api/public/hooks/prestart-missing'
      path: '/api/public/hooks/prestart-missing'
      fullPath: '/api/public/hooks/prestart-missing'
      preLoaderRoute: typeof ApiPublicHooksPrestartMissingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/induction-expiry-sweep': {
      id: '/api/public/hooks/induction-expiry-sweep'
      path: '/api/public/hooks/induction-expiry-sweep'
      fullPath: '/api/public/hooks/induction-expiry-sweep'
      preLoaderRoute: typeof ApiPublicHooksInductionExpirySweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-prompt': {
      id: '/api/public/hooks/daily-prompt'
      path: '/api/public/hooks/daily-prompt'
      fullPath: '/api/public/hooks/daily-prompt'
      preLoaderRoute: typeof ApiPublicHooksDailyPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/allocation-eligibility': {
      id: '/api/public/hooks/allocation-eligibility'
      path: '/api/public/hooks/allocation-eligibility'
      fullPath: '/api/public/hooks/allocation-eligibility'
      preLoaderRoute: typeof ApiPublicHooksAllocationEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AllocationsRouteChildren {
  AllocationsWrapDateRoute: typeof AllocationsWrapDateRoute
}

const AllocationsRouteChildren: AllocationsRouteChildren = {
  AllocationsWrapDateRoute: AllocationsWrapDateRoute,
}

const AllocationsRouteWithChildren = AllocationsRoute._addFileChildren(
  AllocationsRouteChildren,
)

interface PlantIdRouteChildren {
  PlantIdPrestartRoute: typeof PlantIdPrestartRoute
}

const PlantIdRouteChildren: PlantIdRouteChildren = {
  PlantIdPrestartRoute: PlantIdPrestartRoute,
}

const PlantIdRouteWithChildren =
  PlantIdRoute._addFileChildren(PlantIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationsRoute: AllocationsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TodayRoute: TodayRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CrewIdRoute: CrewIdRoute,
  PilesRatesRoute: PilesRatesRoute,
  PlantIdRoute: PlantIdRouteWithChildren,
  ProcureEquipmentRoute: ProcureEquipmentRoute,
  ProcureQuotesRoute: ProcureQuotesRoute,
  ProcureSuppliersRoute: ProcureSuppliersRoute,
  ReportsIdRoute: ReportsIdRoute,
  ReportsExportRoute: ReportsExportRoute,
  SitesIdRoute: SitesIdRoute,
  VariationsIdRoute: VariationsIdRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
  CrewIndexRoute: CrewIndexRoute,
  PilesIndexRoute: PilesIndexRoute,
  PlantIndexRoute: PlantIndexRoute,
  ProcureIndexRoute: ProcureIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SafetyIndexRoute: SafetyIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  SitesIndexRoute: SitesIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  UtilisationIndexRoute: UtilisationIndexRoute,
  VariationsIndexRoute: VariationsIndexRoute,
  ApiPublicSlackWebhookRoute: ApiPublicSlackWebhookRoute,
  PeopleRolesIndexRoute: PeopleRolesIndexRoute,
  PeopleTeamIndexRoute: PeopleTeamIndexRoute,
  PeopleTrainingIndexRoute: PeopleTrainingIndexRoute,
  ApiPublicHooksAllocationEligibilityRoute:
    ApiPublicHooksAllocationEligibilityRoute,
  ApiPublicHooksDailyPromptRoute: ApiPublicHooksDailyPromptRoute,
  ApiPublicHooksInductionExpirySweepRoute:
    ApiPublicHooksInductionExpirySweepRoute,
  ApiPublicHooksPrestartMissingRoute: ApiPublicHooksPrestartMissingRoute,
  ApiPublicHooksPrestartMorningDmRoute: ApiPublicHooksPrestartMorningDmRoute,
  ApiPublicHooksRecomputeReportRoute: ApiPublicHooksRecomputeReportRoute,
  ApiPublicProcurePollGmailRoute: ApiPublicProcurePollGmailRoute,
  ApiPublicReportsPdfRoute: ApiPublicReportsPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
