/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VariationsIndexRouteImport } from './routes/variations.index'
import { Route as UtilisationIndexRouteImport } from './routes/utilisation.index'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SafetyIndexRouteImport } from './routes/safety.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ComplianceIndexRouteImport } from './routes/compliance.index'
import { Route as VariationsIdRouteImport } from './routes/variations.$id'
import { Route as ReportsExportRouteImport } from './routes/reports.export'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as PeopleTrainingIndexRouteImport } from './routes/people.training.index'
import { Route as PeopleTeamIndexRouteImport } from './routes/people.team.index'
import { Route as PeopleRolesIndexRouteImport } from './routes/people.roles.index'
import { Route as ApiPublicSlackWebhookRouteImport } from './routes/api/public/slack-webhook'
import { Route as ApiPublicReportsPdfRouteImport } from './routes/api/public/reports.pdf'
import { Route as ApiPublicHooksRecomputeReportRouteImport } from './routes/api/public/hooks/recompute-report'
import { Route as ApiPublicHooksDailyPromptRouteImport } from './routes/api/public/hooks/daily-prompt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariationsIndexRoute = VariationsIndexRouteImport.update({
  id: '/variations/',
  path: '/variations/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisationIndexRoute = UtilisationIndexRouteImport.update({
  id: '/utilisation/',
  path: '/utilisation/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyIndexRoute = SafetyIndexRouteImport.update({
  id: '/safety/',
  path: '/safety/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/compliance/',
  path: '/compliance/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariationsIdRoute = VariationsIdRouteImport.update({
  id: '/variations/$id',
  path: '/variations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExportRoute = ReportsExportRouteImport.update({
  id: '/reports/export',
  path: '/reports/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleTrainingIndexRoute = PeopleTrainingIndexRouteImport.update({
  id: '/people/training/',
  path: '/people/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleTeamIndexRoute = PeopleTeamIndexRouteImport.update({
  id: '/people/team/',
  path: '/people/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRolesIndexRoute = PeopleRolesIndexRouteImport.update({
  id: '/people/roles/',
  path: '/people/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlackWebhookRoute = ApiPublicSlackWebhookRouteImport.update({
  id: '/api/public/slack-webhook',
  path: '/api/public/slack-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReportsPdfRoute = ApiPublicReportsPdfRouteImport.update({
  id: '/api/public/reports/pdf',
  path: '/api/public/reports/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRecomputeReportRoute =
  ApiPublicHooksRecomputeReportRouteImport.update({
    id: '/api/public/hooks/recompute-report',
    path: '/api/public/hooks/recompute-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyPromptRoute =
  ApiPublicHooksDailyPromptRouteImport.update({
    id: '/api/public/hooks/daily-prompt',
    path: '/api/public/hooks/daily-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/export': typeof ReportsExportRoute
  '/variations/$id': typeof VariationsIdRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/utilisation/': typeof UtilisationIndexRoute
  '/variations/': typeof VariationsIndexRoute
  '/api/public/slack-webhook': typeof ApiPublicSlackWebhookRoute
  '/people/roles/': typeof PeopleRolesIndexRoute
  '/people/team/': typeof PeopleTeamIndexRoute
  '/people/training/': typeof PeopleTrainingIndexRoute
  '/api/public/hooks/daily-prompt': typeof ApiPublicHooksDailyPromptRoute
  '/api/public/hooks/recompute-report': typeof ApiPublicHooksRecomputeReportRoute
  '/api/public/reports/pdf': typeof ApiPublicReportsPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/export': typeof ReportsExportRoute
  '/variations/$id': typeof VariationsIdRoute
  '/compliance': typeof ComplianceIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/safety': typeof SafetyIndexRoute
  '/setup': typeof SetupIndexRoute
  '/utilisation': typeof UtilisationIndexRoute
  '/variations': typeof VariationsIndexRoute
  '/api/public/slack-webhook': typeof ApiPublicSlackWebhookRoute
  '/people/roles': typeof PeopleRolesIndexRoute
  '/people/team': typeof PeopleTeamIndexRoute
  '/people/training': typeof PeopleTrainingIndexRoute
  '/api/public/hooks/daily-prompt': typeof ApiPublicHooksDailyPromptRoute
  '/api/public/hooks/recompute-report': typeof ApiPublicHooksRecomputeReportRoute
  '/api/public/reports/pdf': typeof ApiPublicReportsPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/export': typeof ReportsExportRoute
  '/variations/$id': typeof VariationsIdRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/utilisation/': typeof UtilisationIndexRoute
  '/variations/': typeof VariationsIndexRoute
  '/api/public/slack-webhook': typeof ApiPublicSlackWebhookRoute
  '/people/roles/': typeof PeopleRolesIndexRoute
  '/people/team/': typeof PeopleTeamIndexRoute
  '/people/training/': typeof PeopleTrainingIndexRoute
  '/api/public/hooks/daily-prompt': typeof ApiPublicHooksDailyPromptRoute
  '/api/public/hooks/recompute-report': typeof ApiPublicHooksRecomputeReportRoute
  '/api/public/reports/pdf': typeof ApiPublicReportsPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports/$id'
    | '/reports/export'
    | '/variations/$id'
    | '/compliance/'
    | '/reports/'
    | '/safety/'
    | '/setup/'
    | '/utilisation/'
    | '/variations/'
    | '/api/public/slack-webhook'
    | '/people/roles/'
    | '/people/team/'
    | '/people/training/'
    | '/api/public/hooks/daily-prompt'
    | '/api/public/hooks/recompute-report'
    | '/api/public/reports/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports/$id'
    | '/reports/export'
    | '/variations/$id'
    | '/compliance'
    | '/reports'
    | '/safety'
    | '/setup'
    | '/utilisation'
    | '/variations'
    | '/api/public/slack-webhook'
    | '/people/roles'
    | '/people/team'
    | '/people/training'
    | '/api/public/hooks/daily-prompt'
    | '/api/public/hooks/recompute-report'
    | '/api/public/reports/pdf'
  id:
    | '__root__'
    | '/'
    | '/reports/$id'
    | '/reports/export'
    | '/variations/$id'
    | '/compliance/'
    | '/reports/'
    | '/safety/'
    | '/setup/'
    | '/utilisation/'
    | '/variations/'
    | '/api/public/slack-webhook'
    | '/people/roles/'
    | '/people/team/'
    | '/people/training/'
    | '/api/public/hooks/daily-prompt'
    | '/api/public/hooks/recompute-report'
    | '/api/public/reports/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsExportRoute: typeof ReportsExportRoute
  VariationsIdRoute: typeof VariationsIdRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SafetyIndexRoute: typeof SafetyIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  UtilisationIndexRoute: typeof UtilisationIndexRoute
  VariationsIndexRoute: typeof VariationsIndexRoute
  ApiPublicSlackWebhookRoute: typeof ApiPublicSlackWebhookRoute
  PeopleRolesIndexRoute: typeof PeopleRolesIndexRoute
  PeopleTeamIndexRoute: typeof PeopleTeamIndexRoute
  PeopleTrainingIndexRoute: typeof PeopleTrainingIndexRoute
  ApiPublicHooksDailyPromptRoute: typeof ApiPublicHooksDailyPromptRoute
  ApiPublicHooksRecomputeReportRoute: typeof ApiPublicHooksRecomputeReportRoute
  ApiPublicReportsPdfRoute: typeof ApiPublicReportsPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variations/': {
      id: '/variations/'
      path: '/variations'
      fullPath: '/variations/'
      preLoaderRoute: typeof VariationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisation/': {
      id: '/utilisation/'
      path: '/utilisation'
      fullPath: '/utilisation/'
      preLoaderRoute: typeof UtilisationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/': {
      id: '/safety/'
      path: '/safety'
      fullPath: '/safety/'
      preLoaderRoute: typeof SafetyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variations/$id': {
      id: '/variations/$id'
      path: '/variations/$id'
      fullPath: '/variations/$id'
      preLoaderRoute: typeof VariationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/export': {
      id: '/reports/export'
      path: '/reports/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof ReportsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/training/': {
      id: '/people/training/'
      path: '/people/training'
      fullPath: '/people/training/'
      preLoaderRoute: typeof PeopleTrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/team/': {
      id: '/people/team/'
      path: '/people/team'
      fullPath: '/people/team/'
      preLoaderRoute: typeof PeopleTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/roles/': {
      id: '/people/roles/'
      path: '/people/roles'
      fullPath: '/people/roles/'
      preLoaderRoute: typeof PeopleRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack-webhook': {
      id: '/api/public/slack-webhook'
      path: '/api/public/slack-webhook'
      fullPath: '/api/public/slack-webhook'
      preLoaderRoute: typeof ApiPublicSlackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reports/pdf': {
      id: '/api/public/reports/pdf'
      path: '/api/public/reports/pdf'
      fullPath: '/api/public/reports/pdf'
      preLoaderRoute: typeof ApiPublicReportsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recompute-report': {
      id: '/api/public/hooks/recompute-report'
      path: '/api/public/hooks/recompute-report'
      fullPath: '/api/public/hooks/recompute-report'
      preLoaderRoute: typeof ApiPublicHooksRecomputeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-prompt': {
      id: '/api/public/hooks/daily-prompt'
      path: '/api/public/hooks/daily-prompt'
      fullPath: '/api/public/hooks/daily-prompt'
      preLoaderRoute: typeof ApiPublicHooksDailyPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsIdRoute: ReportsIdRoute,
  ReportsExportRoute: ReportsExportRoute,
  VariationsIdRoute: VariationsIdRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SafetyIndexRoute: SafetyIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  UtilisationIndexRoute: UtilisationIndexRoute,
  VariationsIndexRoute: VariationsIndexRoute,
  ApiPublicSlackWebhookRoute: ApiPublicSlackWebhookRoute,
  PeopleRolesIndexRoute: PeopleRolesIndexRoute,
  PeopleTeamIndexRoute: PeopleTeamIndexRoute,
  PeopleTrainingIndexRoute: PeopleTrainingIndexRoute,
  ApiPublicHooksDailyPromptRoute: ApiPublicHooksDailyPromptRoute,
  ApiPublicHooksRecomputeReportRoute: ApiPublicHooksRecomputeReportRoute,
  ApiPublicReportsPdfRoute: ApiPublicReportsPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
