/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VariationsIndexRouteImport } from './routes/variations.index'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as VariationsIdRouteImport } from './routes/variations.$id'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as ApiPublicSlackWebhookRouteImport } from './routes/api/public/slack-webhook'
import { Route as ApiPublicHooksRecomputeReportRouteImport } from './routes/api/public/hooks/recompute-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariationsIndexRoute = VariationsIndexRouteImport.update({
  id: '/variations/',
  path: '/variations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariationsIdRoute = VariationsIdRouteImport.update({
  id: '/variations/$id',
  path: '/variations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlackWebhookRoute = ApiPublicSlackWebhookRouteImport.update({
  id: '/api/public/slack-webhook',
  path: '/api/public/slack-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRecomputeReportRoute =
  ApiPublicHooksRecomputeReportRouteImport.update({
    id: '/api/public/hooks/recompute-report',
    path: '/api/public/hooks/recompute-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports/$id': typeof ReportsIdRoute
  '/variations/$id': typeof VariationsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/variations/': typeof VariationsIndexRoute
  '/api/public/slack-webhook': typeof ApiPublicSlackWebhookRoute
  '/api/public/hooks/recompute-report': typeof ApiPublicHooksRecomputeReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports/$id': typeof ReportsIdRoute
  '/variations/$id': typeof VariationsIdRoute
  '/reports': typeof ReportsIndexRoute
  '/setup': typeof SetupIndexRoute
  '/variations': typeof VariationsIndexRoute
  '/api/public/slack-webhook': typeof ApiPublicSlackWebhookRoute
  '/api/public/hooks/recompute-report': typeof ApiPublicHooksRecomputeReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports/$id': typeof ReportsIdRoute
  '/variations/$id': typeof VariationsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/variations/': typeof VariationsIndexRoute
  '/api/public/slack-webhook': typeof ApiPublicSlackWebhookRoute
  '/api/public/hooks/recompute-report': typeof ApiPublicHooksRecomputeReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports/$id'
    | '/variations/$id'
    | '/reports/'
    | '/setup/'
    | '/variations/'
    | '/api/public/slack-webhook'
    | '/api/public/hooks/recompute-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports/$id'
    | '/variations/$id'
    | '/reports'
    | '/setup'
    | '/variations'
    | '/api/public/slack-webhook'
    | '/api/public/hooks/recompute-report'
  id:
    | '__root__'
    | '/'
    | '/reports/$id'
    | '/variations/$id'
    | '/reports/'
    | '/setup/'
    | '/variations/'
    | '/api/public/slack-webhook'
    | '/api/public/hooks/recompute-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsIdRoute: typeof ReportsIdRoute
  VariationsIdRoute: typeof VariationsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  VariationsIndexRoute: typeof VariationsIndexRoute
  ApiPublicSlackWebhookRoute: typeof ApiPublicSlackWebhookRoute
  ApiPublicHooksRecomputeReportRoute: typeof ApiPublicHooksRecomputeReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variations/': {
      id: '/variations/'
      path: '/variations'
      fullPath: '/variations/'
      preLoaderRoute: typeof VariationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variations/$id': {
      id: '/variations/$id'
      path: '/variations/$id'
      fullPath: '/variations/$id'
      preLoaderRoute: typeof VariationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack-webhook': {
      id: '/api/public/slack-webhook'
      path: '/api/public/slack-webhook'
      fullPath: '/api/public/slack-webhook'
      preLoaderRoute: typeof ApiPublicSlackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recompute-report': {
      id: '/api/public/hooks/recompute-report'
      path: '/api/public/hooks/recompute-report'
      fullPath: '/api/public/hooks/recompute-report'
      preLoaderRoute: typeof ApiPublicHooksRecomputeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsIdRoute: ReportsIdRoute,
  VariationsIdRoute: VariationsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  VariationsIndexRoute: VariationsIndexRoute,
  ApiPublicSlackWebhookRoute: ApiPublicSlackWebhookRoute,
  ApiPublicHooksRecomputeReportRoute: ApiPublicHooksRecomputeReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
